- name: installing and configuring nginx
  hosts: web
  become: yes
  tasks: 
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: configuring nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes