- name: command vs shell
  hosts: localhost
  tasks::
  - name: command module
    ansible.builtin.command: " echo 'Hello, good morning' > /etc/file1.txt"

  - name: shell module
    ansible.builtin.shell: " echo 'Hello, good morning from shell' > /etc/file2.txt"