- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: " echo 'Hello, good morning' > /tmp/file1.txt"

  - name: shell module
    ansible.builtin.shell: "echo 'Hello, good morning from shell' > /tmp/file.txt"