- name: filters
  hosts: web
  vars:
    greetings: "Hello good morning"
    ages: [12, 25, 65, 44, 25, 65,33]
  tasks:
  - name: default value 
    ansible.builtin.debug:
     msg: " Hello, I'm learning {{ course  | default('Ansible')}}"
  - name: Upper case
    ansible.builtin.debug: 
      msg: " {{greetings | upper }}"
  - name: Lower case
    ansible.builtin.debug:
      msg: " {{greetings | lower }}"
  - name: unique values
    ansible.builtin.debug:
      msg: "Hi, ages listed are : {{ages | unique}}"