- name: filters
  hosts: web
  vars:
    greetings: "Hello good morning"
    ages: [12, 25, 65, 44, 25, 65,33]
    my_dict:
      Name: Harish
      Course: Devops with AWS
      Trainer: Shiva
      Duration: 120hrs
    my_list:
    - {'key': 'Name', 'value': 'Harish'}
    - {'key': 'Course', 'value': 'Devops with AWS'}
    - {'key': 'Trainer', 'value': 'Shiva'}
    - {'key': 'Duration', 'value': '120hrs'}
  tasks:
  - name: default value 
    ansible.builtin.debug:
     msg: " Hello, I'm learning {{ course  | default('Ansible')}}"
  - name: Upper case
    ansible.builtin.debug: 
      msg: " {{greetings | upper }}"
  - name: Lower case
    ansible.builtin.debug:
      msg: " {{greetings | lower }}"
  - name: unique values
    ansible.builtin.debug:
      msg: "Hi, ages listed are : {{ages | unique}}"
  - name: min and max
    ansible.builtin.debug:
     msg: "Min age is : {{ ages | min }},  Max age is : {{ ages | max }}"

  - name: dictionary to list 
    ansible.builtin.debug: 
     msg: "Before converstion: {{my_dict}}"
  - name: dictionary to list 
    ansible.builtin.debug:
     msg: "After convertion: {{my_dict | dict2items}}"
    register: items_list_output
  - name: list to dictionary
    ansible.builtin.debug:
     msg: "List to dictionary:{{ my_list | items2dict }}"


    