- name: conditions
  hosts: web
  become: yes
  tasks:
   - name: check user exist or not 
     ansible.builtin.command: id expense
     register: user
     ignore_errors: true

   - name: user info 
     ansible.builtin.debug:
      msg: " User info : {{user}}"
   - name: create user
     ansible.builtin.command: useradd expense
     when: user.rc != 0 
     
   - name: say Hello
     ansible.builtin.debug:
      msg: "Hello..." 