- name: conditions
  hosts: web
  tasks:
   - name: check user exist or not 
     ansible.builtin.command: id expense
     register: user
     
   - name: Hello
     ansible.builtin.debug:
      msg: "Hello..." 