- name: Loops
  hosts: localhost
  tasks:
  - name: printing loop values
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop:
    - linux
    - ansible
    - shell 



- name: Loops2
  hosts: web
  become: yes
  tasks: 
   - name: installing mysql, postfix and nginx in ansible worker node
  #    ansible.builtin.debug:
  #      msg:"Installing {{items}}"
  #  - name:
     ansible.builtin.command: sudo dnf install {{items}} -y  
     loop:
     - mysql
     - postfix
     - nginx