# - name: Loops
#   hosts: localhost
#   tasks:
#   - name: printing loop values
#     ansible.builtin.debug:
#       msg: "Hello {{item}}"
#     loop:
#     - linux
#     - ansible
#     - shell 



# - name: Loops2
#   hosts: web
#   become: yes
#   tasks: 
#    - name: installing
#   #    ansible.builtin.debug:
#   #      msg:"Installing {{item}}"
#   #  - name:
#      ansible.builtin.dnf: 
#        name: "{{item}}"
#        state: latest
        
#      loop:
#      - mysql
#      - postfix
#      - nginx


- name: installing packages in a loop advanced
  hosts: web
  become: yes
  tasks:
  - name: installing and deleting packages 
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: "installed"}
    - { name: 'mysql', state: "latest"}
    - { name: 'postfix', state: "absent"}