# - name: Loops
#   hosts: localhost
#   tasks:
#   - name: printing loop values
#     ansible.builtin.debug:
#       msg: "Hello {{item}}"
#     loop:
#     - linux
#     - ansible
#     - shell 



- name: Loops2
  hosts: web
  become: yes
  tasks: 
   - name: installing
  #    ansible.builtin.debug:
  #      msg:"Installing {{items}}"
  #  - name:
     ansible.builtin.dnf: 
       name: "{{items}}"
       state: latest
        
     loop:
     - mysql
     - postfix
     - nginx