- name: variables 
  hosts: localhost
  # vars_files:  #variable file 
  # - vars_file.yaml 
  # vars_prompt: #prompt level 
  # - name: Course
  #   prompt: Enter your course name
  #   private: false
  # - name: Trainer
  #   prompt: Enter Trainer name
  #   private: true
  # - name: Duration
  #   prompt: Enter Duration of the courseDuration
  #   private: false
  # vars: #Play level 
  #  Course: Devops with AWS
  #  Trainer: Shiva
  #  Duration: 120hrs
  tasks:
  - name: Devops course details 
    # vars: #task level 
    #   Course: Devops
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Trainer:{{Trainer}}, Duration: {{Duration}}" 

#variable preference
#1.argument level 
#2.task level
#3.variable file 
#4.prompt 
#5.play level
#6.Inventory 
#7. Role level