- name: variables 
  hosts: localhost
  vars_files: 
  - vars_file.yaml 
     
  # vars:
  #  Course: Devops with AWS
  #  Trainer: Shiva
  #  Duration: 120hrs
  tasks:
  - name: Devops course details 
    vars:
      Course: Devops
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Trainer:{{Trainer}}, Duration: {{Duration}}" 