- name: variables 
  hosts: localhost
  # vars_files: 
  # - vars_file.yaml 
  vars_prompt:
  - name: Course
    prompt: Enter your course name
  - name: Trainer
    prompt: Enter Trainer name
  - name: Enter Duration of the course
    prompt: Duration
  # vars:
  #  Course: Devops with AWS
  #  Trainer: Shiva
  #  Duration: 120hrs
  tasks:
  - name: Devops course details 
    # vars:
    #   Course: Devops
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Trainer:{{Trainer}}, Duration: {{Duration}}" 