- name: Installing MySQL server
  ansible.builtin.package:
   name: mysql-server
   state: latest

- name: Staring and enabling mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Installing mysql dependencies
  ansible.builtin.pip:
  - PyMySQL
  - cryptography
  executable: pip3.9

- name: check DB connection
  community.mysql.mysql_info:
    login_user: root
    login_host: " {{ login_host }}"
    login_password: "{{ mysql_root_password }}"
    filter: version
  ignore_erros: yes
  register: mysql_connection_output

- name: print Output
  ansible.builtin.debug:
    msg: "Output: {{ mysql_connection_output }}"
- name: setup root password 
  ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_connection_output.failed is true
   